[build-system]
requires = [ "setuptools>=42", "setuptools-scm[toml]>=3.4", "wheel" ]

[project]
name = "numjuggler"
description = "MCNP input file renumbering tool"
readme = "README.md"
keywords = [ "ITER", "MCNP", "PARSER", "RENUMBER" ]
license = "GPL-3.0-or-later"
authors = [ { name = "A.Travleev", email = "anton.travleev@gmail.com" } ]
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Eduation",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Utilities",
]
dynamic = [ "version" ]
optional-dependencies.nogq = [ "numpy>=2.4.4" ]
urls."Bug Tracker" = "https://github.com/travleev/numjuggler/issues"
urls.Changelog = "https://github.com/travleev/numjuggler/releases"
urls.documentation = "https://numjuggler.readthedocs.io/"
urls.homepage = "https://github.com/travleev/numjuggler/"
urls.repository = "https://github.com/travleev/numjuggler/"
scripts.numjuggler = "numjuggler.main:main"

[dependency-groups]
dev = [
  { include-group = "docs" },
  { include-group = "style" },
  { include-group = "test" },
]
test = [
  "pygments>=2.20",
  "pytest>=9.0.3",
  "pytest-cov>=7.1",
  "pytest-mock>=3.15.1",
  "xdoctest>=1.3.2",
]
docs = [
  "griffe-public-wildcard-imports",
  "mkdocs",
  "mkdocs-include-markdown-plugin",
  "mkdocs-material",
  "mkdocstrings[python]>=0.29",
  "pygments",
]
pylint = [ "pylint", "pylint-per-file-ignores" ]
style = [
  # { include-group = "mypy" },
  #  { include-group = "pyright" },
  "pre-commit>=4.6",
  "ruff>=0.15.11",
  "ty>=0.0.32",
  { include-group = "pylint" },
]

[tool.setuptools_scm]
write_to = "src/numjuggler/version.py"

[tool.coverage]
run.branch = true
run.omit = [ "**/__init__.py", "*_tab.py", "__main__.py", "tools/*.py" ]
run.parallel = true
run.source = [ "src" ]
paths.source = [ "src" ]
# Regexes for lines to exclude from consideration
report.exclude_lines = [
  # Don't complain about missing debug-only code:
  "def __repr__",
  "if __name__ == .__main__.:",
  "if 0:",
  "if self.debug",
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "raise AssertionError",
  "raise NotImplementedError",
]
report.fail_under = 39  # TODO @dvp: should be at least 80%
report.ignore_errors = true
report.omit = [ "**/__init__.py", "**/types.py", "*_tab.py" ]
report.show_missing = true
report.skip_covered = true
report.sort = "Cover"

# MyPy config
# See https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
#     https://dev.to/tusharsadhwani/the-comprehensive-guide-to-mypy-561m

[tool.mypy]
python_version = "3.13"
cache_dir = ".cache/mypy"
files = "src/**/*.py"
follow_imports = "silent"
pretty = true
strict = true
warn_unused_configs = true
overrides = [ { module = [ "tomllib" ], allow_redefinition = true, disable_error_code = "no-redef" } ]

[tool.xdoctest]
quiet = true
options = ""

[tool.jupytext]
# https://jupytext.readthedocs.io/en/latest/config.html
# Pair ipynb notebooks to py:percent text notebooks
formats = "ipynb,py:percent"

[tool.creosote]
paths = [ "src" ]
deps-file = "pyproject.toml"
sections = [ "project.dependencies" ]

[tool.rstcheck]
report_level = "ERROR"
ignore_messages = '(Unknown directive type "(todo.*|automodule)".$)'
